Как-то работает
pastegraph/store-backend pull request #4
Opened 2022-07-24 18:50 UTC by pashabezborod

Формат запроса такой:

POST запрос отправляешь для добавления графа в базу.
В теле запроса должен быть  JSON со следующими полями:

isVisible - (true/false в формате String)
expirationMinutes - сколько будет жить запись с этого момента
graphBody - сам граф (String)

Первые два поля необязательны.
Обратно вернётся ID.

GET запросом получаешь содержимое. Сейчас можно получить только переданный граф.
http://localhost:8080/getGraph/123454321

На другие типы запросов или неправильные запросы получишь ответ с объяснением и кодом.
Тесты нормальные пока не делал, только сам побаловался. Костылей тоже много - со временем буду исправлять. Это всё за день наговнячил.

Посмотри плз, напиши что где переделать

2022-07-25 08:34 UTC, klpx commented on src/main/java/SQLHelper.java
> +                        "downloadTime INTEGER NOT NULL, " +
наверно, ты имеешь в виду "upload time"?

2022-07-25 08:40 UTC, klpx commented on src/main/java/SQLHelper.java
> +                        "jsonData	TEXT, " +
вроде там просто текст, зачем json в названии?

2022-07-25 11:47 UTC, klpx commented on src/main/java/SQLHelper.java
> +                "CREATE TABLE IF NOT EXISTS mainTable (" +
mainTable плохое название, во первых не нужно добавилять "table", ты же не пишешь "idColumn, ipColumn, userAgentColumn" :)
во-вторых, main ни о чем не говорит.
Название должно по сути быть как навзание класса, типа user, post, document...

2022-07-25 11:48 UTC, klpx commented on src/main/java/SQLHelper.java
> +                        "downloadTime INTEGER NOT NULL, " +
наверно, uploadTime все-таки)

2022-07-25 11:49 UTC, klpx commented on src/main/java/timeToLive/Forever.java
> +    }
Непонятно, зачем тут download time

2022-07-25 11:50 UTC, klpx commented on src/main/java/timeToLive/TimeToLive.java
> +    }
зачем download time?

2022-07-25 11:52 UTC, klpx commented on src/main/java/Handler.java
> +                        else makeResponse(graphsMap.get(request[1]).getGraph(), httpExchange, 200);
ты берешь из graphsMap, а не из базы. Получается, что если перзагрузить приложение, то старые записи не будут доступны

2022-07-25 11:52 UTC, klpx commented on src/main/java/Handler.java
> +        } while (graphsMap.containsKey(id));
Это ты хорошо добавил :+1:

2022-07-25 11:56 UTC, klpx commented on src/main/java/ServerMain.java
> +public class ServerMain {
Вообще нужно создать коррневой пакет для приложения.
Типа com.github.pastegraph.store

2022-07-25 11:59 UTC, klpx commented on src/main/java/timeToLive/TimeToLive.java
> +    }
можно же для limited сразу сохранять как надо

2022-07-25 12:03 UTC, klpx requested changes

2022-07-25 12:03 UTC, klpx commented on src/main/java/Handler.java
> +                        else makeResponse(graphsMap.get(request[1]).getGraph(), httpExchange, 200);
ты берешь из graphsMap, а не из базы. Получается, что если перзагрузить приложение, то старые записи не будут доступны

2022-07-25 12:11 UTC, klpx commented on src/main/java/ServerMain.java
> +                            System.exit(1);
А зачем выходить?

2022-07-25 12:12 UTC, klpx commented on src/main/java/ServerMain.java
> +                    if (graphsMap.get(current).getTimeToLive().timeIsUp()) {
Опять же этот код ничего не знает о записях, которые были в базе до старта приложения

2022-07-25 12:13 UTC, klpx commented on src/main/java/SQLHelper.java
> +    public static void connectSqlite(String sqlPath) throws SQLException {
Здесь мог бы быть просто класс :crying_cat_face:

2022-07-25 12:15 UTC, klpx commented on src/main/java/timeToLive/Limited.java
> +        expirationTime = new Date(getDownloadTime().getTime() + 60000L * minToLive);
а почему сюда сразу не передать expirationTime?

2022-07-25 12:16 UTC, klpx commented on src/main/java/timeToLive/Limited.java
> +        expirationTime = new Date(getDownloadTime().getTime() + 60000L * minToLive);
ну или зачем downloadTime тут сохранять?

2022-07-25 12:23 UTC, klpx commented on src/main/java/Handler.java
> +                    List<String> userAgent = httpExchange.getRequestHeaders().get("User-agent");
Много юзер-аргентов это скорее баг, чем фича, поэтому нужно изначально либо взять последний, либо склиеть их каким-нибудь простым образом типа `", "`

2022-07-25 18:48 UTC, pashabezborod commented on src/main/java/Handler.java
> +                    List<String> userAgent = httpExchange.getRequestHeaders().get("User-agent");
Исправил

2022-07-25 18:51 UTC, pashabezborod commented on src/main/java/timeToLive/Limited.java
> +        expirationTime = new Date(getDownloadTime().getTime() + 60000L * minToLive);
Uploadtime хранится для всех записей, в поле абстрактного класса TimeToLive. ExpirationTime всё равно нужно высчитывать, разве важно - делать это тут или в конструкторе GraphItem? Но вычислить можно гораздо проще теперь, это я согласен

2022-07-25 18:53 UTC, pashabezborod commented on src/main/java/timeToLive/Limited.java
> +        expirationTime = new Date(getDownloadTime().getTime() + 60000L * minToLive);
Ок согласен, если вычислять в GraphItem, то нам хватит и одного конструктора

2022-07-25 19:04 UTC, pashabezborod commented on src/main/java/timeToLive/Forever.java
> +    }
Ну ты в задачах указывал, что нужно сохранять время загрузки каждого элемента... Это оно и есть, только я назвал неправильно) Всю информацию о времени загрузки/годности хранит класс TimeToLive. Переименую его в GraphTime,  чтобы было яснее

2022-07-25 19:05 UTC, pashabezborod commented on src/main/java/ServerMain.java
> +public class ServerMain {
Вот тут не совсем понимаю... Как должно в итоге выглядеть? Куда мне пакет main переместить?

2022-07-25 19:09 UTC, pashabezborod commented on src/main/java/Handler.java
> +                        else makeResponse(graphsMap.get(request[1]).getGraph(), httpExchange, 200);
Ну тут дело в особенности реализации. При запуске сервера он сразу читает из БД все записи (метод  readGraphsMap() в мэйне), а дальше хранит во внутренней памяти, а к БД обращается только для операций удаления и добавления элемента. Я подумал, что так ответ на запросы будет приходить быстрей и возникает меньше мест для потенциально критичных ошибок выполнения. Неправильно?

2022-07-25 19:12 UTC, klpx commented on src/main/java/timeToLive/Forever.java
> +    }
Дата загрузки и срок годности это разные свойства, не вижу смысла в однин обхект  объединять

2022-07-25 19:12 UTC, pashabezborod commented on src/main/java/ServerMain.java
> +                            System.exit(1);
Идея в том, что если потеряна связь с БД, значит приложению работать дальше нельзя. А если метод не удалил запись - значит, что-то с БД явно не в порядке. Поэтому голлигую ошибку и выхожу. Неправильный подход?

2022-07-25 19:13 UTC, pashabezborod commented on src/main/java/ServerMain.java
> +                    if (graphsMap.get(current).getTimeToLive().timeIsUp()) {
Знает, выше ответил почему. Если это неверный подход - напиши, переделаю

2022-07-25 19:17 UTC, klpx commented on src/main/java/ServerMain.java
> +public class ServerMain {
В итоге все классы в приложении должны быть в одном пакете com.github.pastegraph.store.* (и глубже, типа com.github.pastegraph.store.exceptions, com.github.pastegraph.store.apps и т.п.)

2022-07-25 19:25 UTC, klpx commented on src/main/java/Handler.java
> +                        else makeResponse(graphsMap.get(request[1]).getGraph(), httpExchange, 200);
Пропустил этот момент.
Ну пока что это сработает - потому что мы запускаем одно приложение, и только оно работает с базой. Хотя все равно могут быть проблемы: например, в случае большой нагрузки sqlite может вернуть ошибку, т. ч. нужно хотя бы убедиться, что операция с базой идет перед внесением изменений в локальную копию - т.е. в случае успешной записи.

В общем случае, если используется не sqltite, а сервер баз данных - то уже не стоит расчитывавть, что работает одна копия приложения, и что получится просто держать копию в памяти.

2022-07-25 19:29 UTC, klpx commented on src/main/java/timeToLive/Limited.java
> +        expirationTime = new Date(getDownloadTime().getTime() + 60000L * minToLive);
ПРоблема не в количестве конструкторов, а в том, что TimeToLive должен нести одну функцию - показывать тебе, когда объект должен быть удален, дата загрузки уже нерелевантна, если у тебя есть конкретная дата удаления.

2022-07-26 20:55 UTC, klpx commented on src/main/java/com/github/pastegraph/store/SQLHelper.java
> +                        "expirationTime INTEGER NOT NULL, " +
uploadTime не хватает)

Я имел в виду что uploadTime и expirationTime это несвязанные сущности, и что не надо их в один класс объединять, но я не имел в виду, что uploadTime не нужен

2022-07-26 20:55 UTC, klpx commented on src/main/java/ServerMain.java
> +                            System.exit(1);
Ну бд может быть не доступна по разным причинам (может запрос с ошибкой отработал или она перегружена), в основном ошибку БД просто логируют

2022-07-26 21:01 UTC, klpx commented on src/main/java/ServerMain.java
> +                    if (graphsMap.get(current).getTimeToLive().timeIsUp()) {
Ты можешь пока оставить, я потом наш сервис поломаю и заведу багу :bug:
Но вообще, лучше работать напрямую с базой.
Во-первых, sqlite и так держит часть или даже все данные в памяти.
Во-вторых, просто держать полную копию означает, что расход памяти будет расти с каждой новой публикацией. Может получиться, что оперативной памяти тупо не хватит)

2022-07-26 21:04 UTC, klpx requested changes
Убери System.exit и верни uploadTime в базу

2022-07-26 21:04 UTC, klpx commented on src/main/java/com/github/pastegraph/store/SQLHelper.java
> +                        "expirationTime INTEGER NOT NULL, " +
uploadTime не хватает)

Я имел в виду что uploadTime и expirationTime это несвязанные сущности, и что не надо их в один класс объединять, но я не имел в виду, что uploadTime не нужен вообще
Прости, если запутал с этим)

2022-07-28 08:09 UTC, klpx commented on .github/workflows/Tests.yml
> +          tags: ${{secrets.DOCKER_NAME}}/pastegraph-store-backend:test
А зачем собирать тут докер? Если есть воркфлоу со сборкой, то он как бы сам себя проверит же.
Это же тупо больше времени/ресуурсов займет. Как разработчик я хочу получать быстрый фидбек о том, что тесты прошли/упали, зачем мне ждать сборку докера?

2022-07-28 08:09 UTC, klpx commented on Dockerfile
> +RUN mvn package
```suggestion
RUN mvn package -Dmaven.test.skip
```

2022-08-02 18:50 UTC, klpx approved these changes

2022-08-02 18:50 UTC, merged